/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Đăng nhập bằng email + password */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description OK — server set refresh token cookie `rt` */
                200: {
                    headers: {
                        /**
                         * @description `rt=<refresh_token>; HttpOnly; Secure; SameSite=Lax; Path=/api/v1/auth;
                         *     Max-Age=604800` (7 ngày). Refresh token lưu rotation với session_id.
                         */
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cấp access token mới, rotation refresh token
         * @description - Gửi refresh token qua cookie `rt` (HttpOnly).
         *     - Server rotate: revoke token cũ, cấp token mới + cookie mới.
         *     - Nếu phát hiện token cũ bị reuse (không khớp session_id / token family)
         *       → revoke toàn bộ session, trả 401 + clear cookie.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK — cấp access token mới, rotate refresh cookie */
                200: {
                    headers: {
                        /**
                         * @description `rt=<refresh_token>; HttpOnly; Secure; SameSite=Lax;
                         *     Path=/api/v1/auth; Max-Age=604800` (7 ngày).
                         */
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: {
                                /** @description JWT access token mới (HS256). */
                                access_token: string;
                                /**
                                 * @description TTL access token (giây).
                                 * @example 900
                                 */
                                expires_in: number;
                            };
                        };
                    };
                };
                /** @description Token invalid / expired / reuse detected */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
                /** @description CSRF — Origin không khớp APP_CORS_ORIGINS */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Đăng xuất — server thu hồi refresh token và clear cookie */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content — logout thành công hoặc idempotent (token thiếu/không hợp lệ) */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description CSRF — Origin không khớp APP_CORS_ORIGINS */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trả thông tin user hiện tại */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            success: true;
                            data: components["schemas"]["User"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Danh sách tài liệu (filter theo scope theo role) */
        get: {
            parameters: {
                query?: {
                    status?: components["schemas"]["DocumentStatus"];
                    type?: string;
                    q?: string;
                    keyword?: string;
                    tags?: string[];
                    page?: number;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["Document"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /**
         * Upload tài liệu mới (trả về job, OCR chạy async)
         * @description - Header `Idempotency-Key: <uuid>` BẮT BUỘC.
         *     - PDF â‰¤ 50MB; JPEG/PNG â‰¤ 10MB; MIME vÃ  magic bytes pháº£i khá»›p `application/pdf`, `image/jpeg` hoáº·c `image/png`.
         *
         *     - Trả 202 Accepted + job_id (FE poll `/jobs/{id}`).
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /**
                         * Format: binary
                         * @description PDF â‰¤ 50MB; JPEG/PNG â‰¤ 10MB; MIME vÃ  magic bytes pháº£i khá»›p.
                         */
                        file: string;
                        title: string;
                        /** @enum {string} */
                        type: "QUY_CHE" | "QUY_DINH" | "THONG_BAO" | "QUYET_DINH" | "HUONG_DAN" | "KHAC";
                        scope: components["schemas"]["DocumentScope"];
                        issuing_body?: string;
                        /** Format: date */
                        effective_from?: string;
                        tags?: string[];
                        change_summary?: string;
                        supersedes_document_id?: string;
                    };
                };
            };
            responses: {
                /** @description Accepted — job đã được queue */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UploadResponse"];
                    };
                };
                400: components["responses"]["ValidationError"];
                403: components["responses"]["Forbidden"];
                409: components["responses"]["Conflict"];
                413: components["responses"]["PayloadTooLarge"];
                415: components["responses"]["UnsupportedMediaType"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{id}/versions/{vid}/ocr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lấy kết quả OCR (pages & blocks) của phiên bản tài liệu */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    requires_review?: boolean;
                    review_status?: components["schemas"]["OCRReviewStatus"];
                };
                header?: never;
                path: {
                    id: string;
                    vid: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: {
                                version_id: string;
                                ocr_status: string;
                                requires_review: boolean;
                                total_blocks: number;
                                pending_reviews: number;
                                pages: components["schemas"]["OCRPage"][];
                                blocks: components["schemas"]["OCRBlock"][];
                            };
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{id}/versions/{vid}/ocr/pages/{page}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lấy ảnh PNG render 300 DPI của một trang OCR
         * @description Backend kiểm tra quyền đọc tài liệu và document scope trước khi lấy object
         *     `image_key` từ storage. Response là bytes PNG qua API; không trả public URL,
         *     presigned URL hoặc storage credential.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    vid: string;
                    page: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description PNG trang OCR */
                200: {
                    headers: {
                        /** @description Không cho shared cache lưu ảnh tài liệu có kiểm soát scope. */
                        "Cache-Control"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "image/png": string;
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{id}/versions/{vid}/ocr/blocks/{bid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Duyệt hoặc chỉnh sửa một block OCR */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    vid: string;
                    bid: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        review_status: components["schemas"]["OCRReviewStatus"];
                        text?: string;
                    };
                };
            };
            responses: {
                /** @description OK — trả về OCR block đã được cập nhật */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["OCRBlock"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
            };
        };
        trace?: never;
    };
    "/documents/{id}/versions/{vid}/ocr/batch-review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Duyệt hàng loạt danh sách các block OCR hoặc chấp nhận toàn bộ block pending */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    vid: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @default false */
                        accept_all_pending?: boolean;
                        actions?: {
                            block_id: string;
                            review_status: components["schemas"]["OCRReviewStatus"];
                            text?: string;
                        }[];
                    };
                };
            };
            responses: {
                /** @description OK — trả về kết quả batch review */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: {
                                reviewed_count: number;
                                remaining_pending_count: number;
                                version_requires_review: boolean;
                            };
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tìm kiếm tài liệu RRF hybrid (Vector + Full-text search) */
        get: {
            parameters: {
                query: {
                    q: string;
                    scope?: components["schemas"]["DocumentScope"];
                    type?: string;
                    keyword?: string;
                    tags?: string[];
                    alpha?: number;
                    top_k?: number;
                    page?: number;
                    size?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK — Kết quả tìm kiếm tài liệu RRF hybrid */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["SearchResponse"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                422: components["responses"]["ValidationError"];
            };
        };
        put?: never;
        /** Tìm kiếm tài liệu RRF hybrid qua POST request body */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SearchQueryRequest"];
                };
            };
            responses: {
                /** @description OK — Kết quả tìm kiếm tài liệu RRF hybrid */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["SearchResponse"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ProblemDetail: {
            /**
             * Format: uri
             * @description URI định danh loại lỗi (cùng origin với API).
             */
            type: string;
            /** @description Tóm tắt ngắn gọn (tiếng Việt). */
            title: string;
            /** @description HTTP status code (mirror). */
            status: number;
            /** @description Mô tả chi tiết (tiếng Việt). */
            detail?: string | null;
            /**
             * @description Mã machine-readable cho auth và domain errors.
             * @enum {string}
             */
            code: "UNAUTHORIZED" | "FORBIDDEN" | "NOT_FOUND" | "VALIDATION_ERROR" | "INVALID_FILE_TYPE" | "IDEMPOTENCY_KEY_MISMATCH" | "RATE_LIMIT" | "CONFLICT" | "INTERNAL" | "AUTH_INVALID_CREDENTIALS" | "AUTH_USER_INACTIVE" | "AUTH_USER_NOT_FOUND" | "AUTH_USER_DISABLED" | "AUTH_MISSING_TOKEN" | "AUTH_INVALID_TOKEN" | "AUTH_TOKEN_EXPIRED" | "AUTH_REFRESH_INVALID" | "AUTH_REFRESH_EXPIRED" | "AUTH_REFRESH_REUSE_DETECTED" | "AUTH_CSRF_ORIGIN_REJECTED" | "AUTH_CSRF_ORIGIN_ABSENT";
            /** @description UUID v7, khớp với log server. */
            request_id: string;
            /** @description Chi tiết validation (optional). */
            errors?: {
                field?: string;
                message?: string;
            }[];
        };
        SuccessEnvelope: {
            /** @enum {boolean} */
            success: true;
            data: unknown;
            total?: number;
            page?: number;
            limit?: number;
        };
        /** @enum {string} */
        DocumentScope: "PUBLIC" | "STUDENT_AFFAIRS" | "INTERNAL";
        /** @enum {string} */
        DocumentStatus: "DRAFT" | "UNDER_REVIEW" | "APPROVED" | "ARCHIVED";
        /** @enum {string} */
        JobStatus: "QUEUED" | "PROCESSING" | "SUCCEEDED" | "FAILED" | "CANCELLED";
        /**
         * @description Trạng thái review cho từng block có `requires_review=true`.
         *     - PENDING: chờ staff/admin xem.
         *     - APPROVED: text OCR đã đúng, không cần sửa.
         *     - CORRECTED: text đã được sửa (cũ → mới lưu ở `original_text`).
         * @enum {string}
         */
        OCRReviewStatus: "PENDING" | "APPROVED" | "CORRECTED";
        User: {
            id: string;
            /** Format: email */
            email: string;
            full_name: string;
            /** @enum {string} */
            role: "admin" | "staff" | "student";
            department?: string | null;
        };
        Document: {
            /** @example doc_01HXYZ... */
            id: string;
            title: string;
            /** @enum {string} */
            type: "QUY_CHE" | "QUY_DINH" | "THONG_BAO" | "QUYET_DINH" | "HUONG_DAN" | "KHAC";
            status: components["schemas"]["DocumentStatus"];
            scope: components["schemas"]["DocumentScope"];
            code_number?: string | null;
            issuing_body?: string | null;
            /** Format: date */
            effective_from?: string | null;
            /** Format: date */
            effective_to?: string | null;
            latest_version: number;
            author_id?: string;
            tags?: string[];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        DocumentVersion: {
            id: string;
            document_id: string;
            version_number: number;
            status: components["schemas"]["DocumentStatus"];
            file_url: string;
            file_size: number;
            /** @description SHA-256 hex */
            checksum: string;
            /** @enum {string} */
            ocr_status: "NOT_STARTED" | "QUEUED" | "PROCESSING" | "SUCCEEDED" | "FAILED";
            /**
             * @description True khi CÓ ÍT NHẤT 1 block có confidence < threshold.
             *     Version chỉ APPROVED khi requires_review=false HOẶC mọi block có
             *     review_status ∈ {APPROVED, CORRECTED}.
             */
            requires_review?: boolean;
            supersedes_version_id?: string | null;
            superseded_by_version_id?: string | null;
            change_summary?: string | null;
            created_by?: string;
            /** Format: date-time */
            created_at: string;
        };
        UploadResponse: {
            /** @enum {boolean} */
            success: true;
            data: {
                document_id: string;
                job_id: string;
                status: components["schemas"]["JobStatus"];
            };
        };
        Job: {
            id: string;
            /** @enum {string} */
            type: "OCR" | "EMBEDDING" | "INDEXING" | "REINDEX";
            status: components["schemas"]["JobStatus"];
            progress?: number;
            error?: string | null;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            finished_at?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        OCRBlock: {
            id: string;
            version_id: string;
            page_id?: string | null;
            page_number: number;
            block_index: number;
            text_content: string;
            confidence: number;
            /** @description [x_min, y_min, x_max, y_max] theo pixel ảnh render 300 DPI */
            bbox: number[];
            requires_review: boolean;
            review_status: components["schemas"]["OCRReviewStatus"];
            edited_text?: string | null;
            original_text?: string | null;
            job_id?: string | null;
            reviewed_by?: string | null;
            /** Format: date-time */
            reviewed_at?: string | null;
            processing_time_ms?: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        OCRPage: {
            id: string;
            version_id: string;
            page_number: number;
            width?: number | null;
            height?: number | null;
            /** @description Object key nội bộ; chỉ dùng để quyết định có ảnh, không hiển thị cho client. */
            image_key?: string | null;
            status: string;
            block_count: number;
            has_warnings: boolean;
            /** Format: date-time */
            created_at: string;
        };
        SearchResultItem: {
            chunk_id: string;
            document_id: string;
            version_id: string;
            document_title: string;
            document_scope: string;
            document_type: string;
            page_number: number;
            chunk_index: number;
            text: string;
            bbox: number[];
            score: number;
            vector_score?: number | null;
            fulltext_score?: number | null;
        };
        SearchResponse: {
            items: components["schemas"]["SearchResultItem"][];
            total: number;
            page: number;
            size: number;
            query: string;
        };
        SearchQueryRequest: {
            query: string;
            scope?: components["schemas"]["DocumentScope"];
            doc_type?: string;
            /** @description Lọc bổ sung không phân biệt hoa thường trên metadata title, code_number, issuing_body hoặc tag; không thay thế query RAG chính. */
            keyword?: string;
            /** @description Chỉ giữ tài liệu có đầy đủ các tag được yêu cầu, so khớp exact không phân biệt hoa thường. */
            tags?: string[];
            /** @default 0.5 */
            alpha: number;
            /** @default 10 */
            top_k: number;
            /** @default 1 */
            page: number;
            /** @default 10 */
            size: number;
        };
        Citation: {
            document_id: string;
            document_version_id: string;
            title: string;
            page_number: number;
            chunk_id: string;
            quote: string;
            score: number;
            /** @description [x_min, y_min, x_max, y_max] */
            bbox?: number[];
        };
        ChatResponse: {
            /** @enum {boolean} */
            success: true;
            data: {
                answer: string;
                citations: components["schemas"]["Citation"][];
                has_sufficient_evidence: boolean;
            };
        };
        LoginResponse: {
            /** @enum {boolean} */
            success: true;
            data: {
                /**
                 * @description JWT access token. FE giữ trong memory, KHÔNG lưu localStorage.
                 *     Gắn vào `Authorization: Bearer <access_token>`.
                 */
                access_token: string;
                /**
                 * @description Luôn là "bearer" — tuân chuẩn RFC 6750.
                 * @enum {string}
                 */
                token_type?: "bearer";
                /** @description TTL của access token (giây). */
                expires_in: number;
                user: components["schemas"]["User"];
            };
        };
    };
    responses: {
        /** @description Chưa xác thực hoặc token hết hạn */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Thiếu permission */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Resource không tồn tại */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Dữ liệu không hợp lệ */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Conflict (duplicate, version cũ) */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description File vượt quá 50MB */
        PayloadTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description MIME không hỗ trợ */
        UnsupportedMediaType: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Quá nhiều request */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
