/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Đăng nhập bằng email + password */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description OK — server set refresh token cookie `rt` */
                200: {
                    headers: {
                        /**
                         * @description `rt=<refresh_token>; HttpOnly; Secure; SameSite=Lax; Path=/api/v1/auth;
                         *     Max-Age=604800` (7 ngày). Refresh token lưu rotation với session_id.
                         */
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cấp access token mới, rotation refresh token
         * @description - Gửi refresh token qua cookie `rt` (HttpOnly).
         *     - Server rotate: revoke token cũ, cấp token mới + cookie mới.
         *     - Nếu phát hiện token cũ bị reuse (không khớp session_id / token family)
         *       → revoke toàn bộ session, trả 401 + clear cookie.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        /** @description Cookie `rt` mới. */
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            success: true;
                            data: {
                                access_token: string;
                                expires_in: number;
                            };
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Đăng xuất — server thu hồi refresh token và clear cookie */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content — server clear cookie `rt` */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trả thông tin user hiện tại */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            success: true;
                            data: components["schemas"]["User"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Danh sách tài liệu (filter theo scope theo role) */
        get: {
            parameters: {
                query?: {
                    status?: components["schemas"]["DocumentStatus"];
                    type?: string;
                    q?: string;
                    page?: number;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["Document"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /**
         * Upload tài liệu mới (trả về job, OCR chạy async)
         * @description - Header `Idempotency-Key: <uuid>` BẮT BUỘC.
         *     - PDF ≤ 50MB, MIME = application/pdf, magic bytes %PDF-.
         *     - Trả 202 Accepted + job_id (FE poll `/jobs/{id}`).
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /**
                         * Format: binary
                         * @description PDF ≤ 50MB
                         */
                        file: string;
                        title: string;
                        /** @enum {string} */
                        type: "QUY_CHE" | "QUY_DINH" | "THONG_BAO" | "QUYET_DINH" | "HUONG_DAN" | "KHAC";
                        scope: components["schemas"]["DocumentScope"];
                        issuing_body?: string;
                        /** Format: date */
                        effective_from?: string;
                        tags?: string[];
                        change_summary?: string;
                        supersedes_document_id?: string;
                    };
                };
            };
            responses: {
                /** @description Accepted — job đã được queue */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UploadResponse"];
                    };
                };
                400: components["responses"]["ValidationError"];
                403: components["responses"]["Forbidden"];
                409: components["responses"]["Conflict"];
                413: components["responses"]["PayloadTooLarge"];
                415: components["responses"]["UnsupportedMediaType"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ProblemDetail: {
            /**
             * Format: uri
             * @description URI định danh loại lỗi (cùng origin với API).
             */
            type: string;
            /** @description Tóm tắt ngắn gọn (tiếng Việt). */
            title: string;
            /** @description HTTP status code (mirror). */
            status: number;
            /** @description Mô tả chi tiết (tiếng Việt). */
            detail?: string | null;
            /**
             * @description Mã machine-readable.
             * @enum {string}
             */
            code: "UNAUTHORIZED" | "FORBIDDEN" | "NOT_FOUND" | "VALIDATION_ERROR" | "INVALID_FILE_TYPE" | "IDEMPOTENCY_KEY_MISMATCH" | "RATE_LIMIT" | "CONFLICT" | "INTERNAL";
            /** @description UUID v7, khớp với log server. */
            request_id: string;
            /** @description Chi tiết validation (optional). */
            errors?: {
                field?: string;
                message?: string;
            }[];
        };
        SuccessEnvelope: {
            /** @enum {boolean} */
            success: true;
            data: unknown;
            total?: number;
            page?: number;
            limit?: number;
        };
        /** @enum {string} */
        DocumentScope: "PUBLIC" | "STUDENT_AFFAIRS" | "INTERNAL";
        /** @enum {string} */
        DocumentStatus: "DRAFT" | "UNDER_REVIEW" | "APPROVED" | "ARCHIVED";
        /** @enum {string} */
        JobStatus: "QUEUED" | "PROCESSING" | "SUCCEEDED" | "FAILED" | "CANCELLED";
        /**
         * @description Trạng thái review cho từng block có `requires_review=true`.
         *     - PENDING: chờ staff/admin xem.
         *     - APPROVED: text OCR đã đúng, không cần sửa.
         *     - CORRECTED: text đã được sửa (cũ → mới lưu ở `original_text`).
         * @enum {string}
         */
        OCRReviewStatus: "PENDING" | "APPROVED" | "CORRECTED";
        User: {
            id: string;
            /** Format: email */
            email: string;
            full_name: string;
            /** @enum {string} */
            role: "admin" | "staff" | "student";
            department?: string | null;
        };
        Document: {
            /** @example doc_01HXYZ... */
            id: string;
            title: string;
            /** @enum {string} */
            type: "QUY_CHE" | "QUY_DINH" | "THONG_BAO" | "QUYET_DINH" | "HUONG_DAN" | "KHAC";
            status: components["schemas"]["DocumentStatus"];
            scope: components["schemas"]["DocumentScope"];
            code_number?: string | null;
            issuing_body?: string | null;
            /** Format: date */
            effective_from?: string | null;
            /** Format: date */
            effective_to?: string | null;
            latest_version: number;
            author_id?: string;
            tags?: string[];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        DocumentVersion: {
            id: string;
            document_id: string;
            version_number: number;
            status: components["schemas"]["DocumentStatus"];
            file_url: string;
            file_size: number;
            /** @description SHA-256 hex */
            checksum: string;
            /** @enum {string} */
            ocr_status: "NOT_STARTED" | "QUEUED" | "PROCESSING" | "SUCCEEDED" | "FAILED";
            /**
             * @description True khi CÓ ÍT NHẤT 1 block có confidence < threshold.
             *     Version chỉ APPROVED khi requires_review=false HOẶC mọi block có
             *     review_status ∈ {APPROVED, CORRECTED}.
             */
            requires_review?: boolean;
            supersedes_version_id?: string | null;
            superseded_by_version_id?: string | null;
            change_summary?: string | null;
            created_by?: string;
            /** Format: date-time */
            created_at: string;
        };
        UploadResponse: {
            /** @enum {boolean} */
            success: true;
            data: {
                document_id: string;
                job_id: string;
                status: components["schemas"]["JobStatus"];
            };
        };
        Job: {
            id: string;
            /** @enum {string} */
            type: "OCR" | "EMBEDDING" | "INDEXING" | "REINDEX";
            status: components["schemas"]["JobStatus"];
            progress?: number;
            error?: string | null;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            finished_at?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        OCRBlock: {
            id: string;
            ocr_job_id: string;
            page_number: number;
            /** @description [x_min, y_min, x_max, y_max] trong PDF coordinate */
            bbox?: number[];
            text: string;
            confidence: number;
            /**
             * @description True khi confidence < threshold (mặc định 0.9).
             *     Cờ này quyết định version `requires_review=true`.
             */
            requires_review: boolean;
            review_status: components["schemas"]["OCRReviewStatus"];
            reviewed_by?: string | null;
            /** Format: date-time */
            reviewed_at?: string | null;
            /**
             * @description True khi `text` đã khác `original_text` (sửa lỗi).
             *     Nên giữ cho compatibility, nhưng review mới dùng `review_status`.
             */
            is_edited?: boolean;
            edited_by?: string | null;
            /** Format: date-time */
            edited_at?: string | null;
            original_text?: string | null;
            processing_time_ms?: number;
        };
        Citation: {
            document_id: string;
            document_version_id: string;
            title: string;
            page_number: number;
            chunk_id: string;
            quote: string;
            score: number;
            /** @description [x_min, y_min, x_max, y_max] */
            bbox?: number[];
        };
        ChatResponse: {
            /** @enum {boolean} */
            success: true;
            data: {
                answer: string;
                citations: components["schemas"]["Citation"][];
                has_sufficient_evidence: boolean;
            };
        };
        LoginResponse: {
            /** @enum {boolean} */
            success: true;
            data: {
                /**
                 * @description JWT access token. FE giữ trong memory, KHÔNG lưu localStorage.
                 *     Gắn vào `Authorization: Bearer <access_token>`.
                 */
                access_token: string;
                /** @description TTL của access token (giây). */
                expires_in: number;
                user: components["schemas"]["User"];
            };
        };
    };
    responses: {
        /** @description Chưa xác thực hoặc token hết hạn */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Thiếu permission */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Resource không tồn tại */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Dữ liệu không hợp lệ */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Conflict (duplicate, version cũ) */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description File vượt quá 50MB */
        PayloadTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description MIME không hỗ trợ */
        UnsupportedMediaType: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Quá nhiều request */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
